In [1]:
import pandas as pd

In [2]:
train_df = pd.read_pickle("train.pkl")
test_df = pd.read_pickle("test.pkl")

In [3]:
train_df.shape

(1458644, 14)

### Train Data

In [4]:
# Prune rows where trip duration is less than 60 or higher than 7200.

train_df = train_df.query("(60 < trip_duration < 7200)")

train_df.shape[0]

1447614

In [5]:
# Prune rows where longitude is not between -73 and -74.5.
# Prune rows where latitude is not between 40 and 41.

train_df = train_df.query("(-74.5 < pickup_longitude < -73)")
train_df = train_df.query("(-74.5 < dropoff_longitude < -73)")

train_df = train_df.query("(40 < pickup_latitude < 41)")
train_df = train_df.query("(40 < dropoff_latitude < 41)")

train_df.shape[0]

1447358

In [6]:
# Prune rows where trip distance is more than 60.

train_df = train_df.query("trip_distance < 60")

train_df.shape[0]

1447358

In [7]:
# Add "is_rush_hour" column.

train_df["is_rush_hour"] = (((14 <= train_df["pickup_hour"]) & (train_df["pickup_hour"] <= 16)) \
                            & ((0 <= train_df["pickup_day_of_week"]) & (train_df["pickup_day_of_week"] <= 5))).astype(bool)

train_df[train_df["is_rush_hour"] == True].shape[0]

train_df.head()

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455,0.019859,0,17,False
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663,0.026478,6,0,False
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124,0.080158,1,11,False
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429,0.015480,2,19,False
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435,0.010818,5,13,False

In [8]:
train_df = train_df.drop(columns=["id", "pickup_datetime", "dropoff_datetime", "store_and_fwd_flag"])

train_df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,2,1,-73.982155,40.767937,-73.964630,40.765602,455,0.019859,0,17,False
1,1,1,-73.980415,40.738564,-73.999481,40.731152,663,0.026478,6,0,False
2,2,1,-73.979027,40.763939,-74.005333,40.710087,2124,0.080158,1,11,False
3,2,1,-74.010040,40.719971,-74.012268,40.706718,429,0.015480,2,19,False
4,2,1,-73.973053,40.793209,-73.972923,40.782520,435,0.010818,5,13,False

### Test Data

In [9]:
# Add "is_rush_hour" column.

test_df["is_rush_hour"] = (((14 <= test_df["pickup_hour"]) & (test_df["pickup_hour"] <= 16)) \
                            & ((0 <= test_df["pickup_day_of_week"]) & (test_df["pickup_day_of_week"] <= 5))).astype(bool)

test_df[test_df["is_rush_hour"] == True].shape[0]

test_df.head()

,id,vendor_id,pickup_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,id3004672,1,2016-06-30 23:59:58,1,-73.988129,40.732029,-73.990173,40.756680,N,0.026695,3,23,False
1,id3505355,1,2016-06-30 23:59:53,1,-73.964203,40.679993,-73.959808,40.655403,N,0.028984,3,23,False
2,id1217141,1,2016-06-30 23:59:47,1,-73.997437,40.737583,-73.986160,40.729523,N,0.019337,3,23,False
3,id2150126,2,2016-06-30 23:59:41,1,-73.956070,40.771900,-73.986427,40.730469,N,0.071789,3,23,False
4,id1598245,1,2016-06-30 23:59:33,1,-73.970215,40.761475,-73.961510,40.755890,N,0.014290,3,23,False

In [10]:
# Save test.csv "id" column seperately for submission.

test_df_id_col = test_df["id"]

test_df_id_col

0         id3004672
1         id3505355
2         id1217141
3         id2150126
4         id1598245
            ...
625129    id3008929
625130    id3700764
625131    id2568735
625132    id1384355
625133    id0621643
Name: id, Length: 625134, dtype: object

In [11]:
test_df = test_df.drop(columns=["id", "pickup_datetime", "store_and_fwd_flag"])

test_df.head()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,1,1,-73.988129,40.732029,-73.990173,40.756680,0.026695,3,23,False
1,1,1,-73.964203,40.679993,-73.959808,40.655403,0.028984,3,23,False
2,1,1,-73.997437,40.737583,-73.986160,40.729523,0.019337,3,23,False
3,2,1,-73.956070,40.771900,-73.986427,40.730469,0.071789,3,23,False
4,1,1,-73.970215,40.761475,-73.961510,40.755890,0.014290,3,23,False

### Final Touches

In [12]:
train_df

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,2,1,-73.982155,40.767937,-73.964630,40.765602,455,0.019859,0,17,False
1,1,1,-73.980415,40.738564,-73.999481,40.731152,663,0.026478,6,0,False
2,2,1,-73.979027,40.763939,-74.005333,40.710087,2124,0.080158,1,11,False
3,2,1,-74.010040,40.719971,-74.012268,40.706718,429,0.015480,2,19,False
4,2,1,-73.973053,40.793209,-73.972923,40.782520,435,0.010818,5,13,False
...,...,...,...,...,...,...,...,...,...,...,...
1458639,2,4,-73.982201,40.745522,-73.994911,40.740170,778,0.018063,4,13,False
1458640,1,1,-74.000946,40.747379,-73.970184,40.796547,655,0.079929,6,7,False
1458641,2,1,-73.959129,40.768799,-74.004433,40.707371,764,0.106731,4,6,False
1458642,1,1,-73.982079,40.749062,-73.974632,40.757107,373,0.015491,1,15,True
1458643,1,1,-73.979538,40.781750,-73.972809,40.790585,198,0.015564,1,14,True

In [13]:
test_df

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_distance,pickup_day_of_week,pickup_hour,is_rush_hour
0,1,1,-73.988129,40.732029,-73.990173,40.756680,0.026695,3,23,False
1,1,1,-73.964203,40.679993,-73.959808,40.655403,0.028984,3,23,False
2,1,1,-73.997437,40.737583,-73.986160,40.729523,0.019337,3,23,False
3,2,1,-73.956070,40.771900,-73.986427,40.730469,0.071789,3,23,False
4,1,1,-73.970215,40.761475,-73.961510,40.755890,0.014290,3,23,False
...,...,...,...,...,...,...,...,...,...,...
625129,1,1,-74.003464,40.725105,-74.001251,40.733643,0.010750,4,0,False
625130,1,1,-74.006363,40.743782,-73.953407,40.782467,0.091640,4,0,False
625131,1,2,-73.972267,40.759865,-73.876602,40.748665,0.106865,4,0,False
625132,1,1,-73.976501,40.733562,-73.854263,40.891788,0.280464,4,0,False
625133,2,2,-73.981850,40.716881,-73.969330,40.769379,0.065018,4,0,False

In [14]:
train_df.to_pickle("train_df_clean.pkl")
test_df.to_pickle("test_df_clean.pkl")
test_df_id_col.to_pickle("test_df_id_col.pkl")